### ISSUE TITLE
PiRogue - Missing dependency

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/deb-python#1]
We have to add `libimobiledevice-utils` into `mvt/debian/control`

**Comment by CyrilBrulebois** [comment]
For context, this is about supporting: https://pts-project.org/docs/recipes/device-forensic-with-mvt/#forensic-of-an-ios-device

As discussed, it might make sense to have that declared in the mvt package, but some pirogue-* metapackage would be better as there's no code in mvt (or its dependencies) calling `idevice*` tools.
